server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/Quizguru/protocol/openid-connect/certs

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# keycloak:
#   auth-server-url: http://localhost:7080
#   realm: Quizguru
#   resource: quizguru-cc
#   credentials:
#     secret: 3PIOPp92fBvTkT8OjhkTtMs1i6hlB3xv