server:
  port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/quizguru_auth
    username: root
    password: k989898k
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always  

logging:
  level:
    root: DEBUG 
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: auth-server

jwt:
  secret: WUSGVBKJADNFN893745897IWOHFCASNCLANWIVBKGWFEKGSUIHVKSJVNJKBWSVKWB
  expirationMs: 1800000 # 30 min
refreshToken:
  expirationMs: 3600000 # 1 hour
verificationToken:
  expirationMs: 3600000 # 1 hour
passwordResetToken:
  expirationMs: 3600000 # 1 hour

amqp:
  exchanges:
    internal: internal.exchange
  queues:
    verification-mail: verification-mail.queue
    password-reset-mail: password-reset-mail.queue
    base-mail: base-mail.queue 
  routing-keys:
    internal-verification-mail: internal.verification-mail.routing-key
    internal-password-reset-mail: internal.password-reset-mail.routing-key
    internal-base-mail: internal.base-mail.routing-key