server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/quizguru_user
    username: root
    password: k989898k
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

amqp:
  queues:
    verification-mail: verification-mail.queue
    password-reset-mail: password-reset-mail.queue 
    base-mail: base-mail.queue 

javaMailSender:
  host: smtp.gmail.com
  port: 587
  username: duckhailinux@gmail.com
  password: '{cipher}bdbd34577b1eafe13de12aab98b65c214b89f1bacdf468ed7c31cf53bb7678f0ed86bcfd321e8746c2e253eec4fb3b44'